<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>HeavyModManager.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HipHopTool\HipHopFile\HipHopFile.csproj" />
    <PackageReference Include="GCNTools" Version="1.0.2" />
  </ItemGroup>

</Project>
