<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Resources\icon_rainbow.ico</ApplicationIcon>
    <StartupObject>HeavyModManager.Program</StartupObject>
  </PropertyGroup>

  <PropertyGroup Condition="!$([MSBuild]::IsOSPlatform('Windows'))">
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup Condition="!$([MSBuild]::IsOSPlatform('Windows'))">
    <Compile Remove="**/*.cs" />
    <EmbeddedResource Remove="**/*.resx" />
    <None Include="**/*" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <ProjectReference Include="..\HipHopTool\HipHopFile\HipHopFile.csproj" />
    <ProjectReference Include="..\HeavyModManager.Core\HeavyModManager.Core.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <Compile Update="Forms\GlobalResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GlobalResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <EmbeddedResource Update="Forms\GlobalResources.pt.resx">
      <SubType>Designer</SubType>
      <LastGenOutput>GlobalResources - Copy.de.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Forms\GlobalResources.de.resx">
      <LastGenOutput>GlobalResources.de.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Forms\GlobalResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>GlobalResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Forms\MainForm.de.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Forms\MainForm.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <PackageReference Include="GCNTools" Version="1.0.2" />
  </ItemGroup>

</Project>