//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeavyModManager.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeavyModManager.Forms.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpongeBob SquarePants: Battle for Bikini Bottom.
        /// </summary>
        internal static string bfbbName {
            get {
                return ResourceManager.GetString("bfbbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Guy: Back to the Multiverse.
        /// </summary>
        internal static string bttmName {
            get {
                return ResourceManager.GetString("bttmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harley Pasternak&apos;s Hollywood Workout.
        /// </summary>
        internal static string hollywoodWorkoutName {
            get {
                return ResourceManager.GetString("hollywoodWorkoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Incredibles.
        /// </summary>
        internal static string incrediblesName {
            get {
                return ResourceManager.GetString("incrediblesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratatouille.
        /// </summary>
        internal static string ratName {
            get {
                return ResourceManager.GetString("ratName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratatouille (Jan 18, 2006 prototype).
        /// </summary>
        internal static string ratProtoName {
            get {
                return ResourceManager.GetString("ratProtoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Incredibles: Rise of the Underminer.
        /// </summary>
        internal static string rotuName {
            get {
                return ResourceManager.GetString("rotuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scooby-Doo: Night of 100 Frights.
        /// </summary>
        internal static string scoobyName {
            get {
                return ResourceManager.GetString("scoobyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpongeBob&apos;s Truth or Square.
        /// </summary>
        internal static string tosName {
            get {
                return ResourceManager.GetString("tosName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SpongeBob SquarePants Movie.
        /// </summary>
        internal static string tssmName {
            get {
                return ResourceManager.GetString("tssmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UFC Personal Trainer.
        /// </summary>
        internal static string ufcName {
            get {
                return ResourceManager.GetString("ufcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string upName {
            get {
                return ResourceManager.GetString("upName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WALL-E.
        /// </summary>
        internal static string wallEName {
            get {
                return ResourceManager.GetString("wallEName", resourceCulture);
            }
        }
    }
}
